[package]
name = "mpd-futures"
version = "0.1.0"
authors = ["Sam Lakerveld <darkwater124@gmail.com>"]

[dependencies]
futures       = "^0.1.14"
tokio-io      = "^0.1.2"
tokio-core    = "^0.1.8"
tokio-proto   = "^0.1.1"
tokio-service = "^0.1.0"
